language: node_js
node_js:
  - "12"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install -g swagger-cli
  - npm install -g openapi-to-postmanv2
script:
  - npm run build
  - npm run postman
  - npm test

deploy:
  - provider: releases
    skip_cleanup: true
    file:
      - _build/openapi3.yaml
      - _build/postman.json
    api_key: $GITHUB_TOKEN
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: _build
    on:
      branch: master
